language: node_js
node_js:
- '5'
before_install:
  - npm instal -g bower
  - npm install -g karma-cli
  - bower install
script:
  - karma start config/karma.config.js --single-run --browsers PhantomJS
